### ISSUE TITLE
Application fails when running as single file executable

### ISSUE THREAD

**Issue by Lukas-Holecy** [Lukas-Holecy/DependencyGraph#25]
**Describe the bug**
Application errors when run from a self contained single file executable with error:

> Unhandled exception. System.InvalidOperationException: Failed to infer the default application executable name. Please specify it explicitly using `SetExecutableName()`.
>    at CliFx.CliApplicationBuilder.GetDefaultExecutableName() in /_/CliFx/CliApplicationBuilder.cs:line 253
>    at CliFx.CliApplicationBuilder.Build() in /_/CliFx/CliApplicationBuilder.cs:line 205
>    at Holecy.Console.Dependencies.Program.Main(String[] args)
>    at Holecy.Console.Dependencies.Program.<Main>(String[] args)

**To Reproduce**
When I try to run it like this:
1. Create a self contained single file exe file using command `dotnet publish -r win-x64 --sc true -c Release /p:PublishSingleFile=true /p:UseAppHost=true`
2. Run the application `.\DependencyGraphGenerator.exe "../../Repos/OfficeUtilities" --output-type "all" --output-path  "./out/" --filter "LocalPath" --image "all" --imagePath "./images/" --project-filter "Brochet.Common.Common"`
3. See error

> Unhandled exception. System.InvalidOperationException: Failed to infer the default application executable name. Please specify it explicitly using `SetExecutableName()`.
>    at CliFx.CliApplicationBuilder.GetDefaultExecutableName() in /_/CliFx/CliApplicationBuilder.cs:line 253
>    at CliFx.CliApplicationBuilder.Build() in /_/CliFx/CliApplicationBuilder.cs:line 205
>    at Holecy.Console.Dependencies.Program.Main(String[] args)
>    at Holecy.Console.Dependencies.Program.<Main>(String[] args)
> ```

**Expected behavior**
Application should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows x64

**Comment by Lukas-Holecy** [comment]
Fixed in 35b533f982b7137b9203f6f709cf32879516e536. The name of the application had to be explicitly set in main method.
